seed_everything: 42

# ---------------------------- TRAINER -------------------------------------------
trainer:
  default_root_dir: ./exps/climate_projection_custom
  precision: 32  # Use 32 for CPU
  devices: 1
  accelerator: cpu
  max_epochs: 5  # Short training for testing
  enable_progress_bar: true
  enable_checkpointing: true
  fast_dev_run: false

# ---------------------------- MODEL -------------------------------------------
model:
  lr: 5e-4
  beta_1: 0.9
  beta_2: 0.999
  weight_decay: 1e-5
  warmup_epochs: 2
  max_epochs: 5
  warmup_start_lr: 1e-8
  eta_min: 1e-8
  pretrained_path: ""

  net:
    class_path: climax.climate_projection.arch.ClimaXClimateBench
    init_args:
      default_vars: ['CO2']
      out_vars: "tas"
      img_size: [150, 277]
      time_history: 10
      patch_size: 4  # Larger patch size to reduce computation
      embed_dim: 256  # Smaller embedding
      depth: 4  # Fewer layers
      num_heads: 4
      mlp_ratio: 4
      drop_path: 0.1
      drop_rate: 0.1
      parallel_patch_embed: false
      freeze_encoder: false

# ---------------------------- DATA -------------------------------------------
data:
  root_dir: ./climax_data/
  history: 10
  list_train_simu: ['ssp585', 'historical']
  list_test_simu: ['ssp585']
  variables: ['CO2']
  out_variables: 'tas'
  train_ratio: 0.9
  batch_size: 1  # Very small batch size for testing
  num_workers: 0
  pin_memory: false